credentials:
  username: "example@example.com"
  password: "ExamplePassword123"

monitoring:
  timeout: PT30S  # 30 second timeout for requests

exam:
  category: "B"
  wordId: "43" # Gdansk
  checkInterval: PT10S
  startDate: "2025-05-08"
  endDate: "2025-06-29"
  examType: "practice"  # options: practice, theory, both

notification:
  discord: true
  webhookUrl: "https://discord.com/api/webhooks/example-webhook-url"
